from django.db import models

# Create your models here.
from django.db import models

class Usuario(models.Model):
    nombreCompleto = models.CharField( max_length=30)
    rol = models.CharField( max_length=30)
    contrasena= models.CharField(max_length=128, default='123')
    ano_nacimiento=models.CharField(max_length=30, default='123')
    pais=models.CharField(max_length=30)
    telefono = models.CharField( max_length=30)
    correo = models.CharField( max_length=30)
    genero = models.CharField( max_length=30, default="")

class Importacion(models.Model):
    idImportacion=models.IntegerField(primary_key = True, help_text="ID unico para el tipo")
    fechaDeclaracion = models.CharField()
    proveedor = models.CharField( max_length=30)
    descripcionMercancia = models.CharField( max_length=100)
    codigoArancelario = models.BigIntegerField()
    cantidad = models.IntegerField()
    unidadMedida = models.CharField( max_length=30)
    valorCif = models.FloatField()
    impuestos = models.FloatField()
    origenMercancia = models.CharField( max_length=30)
    puertoEntrada = models.CharField( max_length=30)
    transporteID = models.ForeignKey('Transporte', on_delete=models.SET_NULL, null=True)
    responsableID = models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)

class Exportacion(models.Model):
    idExportacion=models.IntegerField(primary_key = True, help_text="ID unico para el tipo")
    fechaDeclaracion = models.CharField()
    cliente = models.CharField( max_length=30)
    descripcionMercancia = models.CharField( max_length=100)
    codigoArancelario = models.BigIntegerField()
    cantidad = models.IntegerField()
    unidadMedida = models.CharField( max_length=30)
    valorFob = models.FloatField()
    impuestos = models.CharField( max_length=30)
    destinoMercancia = models.CharField( max_length=30)
    puertoSalida = models.CharField( max_length=30)
    transporteID = models.ForeignKey('Transporte', on_delete=models.SET_NULL, null=True)
    responsableID = models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)

class Carga(models.Model):
    idCarga = models.IntegerField(primary_key= True, help_text= "ID unico para el tipo")
    tipoCarga = models.CharField(max_length=30)
    descripcionCarga = models.CharField(max_length=100)
    pesoBruto = models.DecimalField(max_digits=5, decimal_places=2)
    pesoNeto = models.DecimalField(max_digits=5, decimal_places=2)
    volumen = models.DecimalField(max_digits=5, decimal_places=2)
    embalaje = models.CharField( max_length=30)
    contenido = models.CharField( max_length=30)
    valorDeclarado =  models.FloatField()
    seguroCarga = models.FloatField()
    estadoCarga = models.CharField( max_length=30)
    idImportacion = models.ForeignKey('Importacion', on_delete=models.SET_NULL, null=True)
    idExportacion = models.ForeignKey('Exportacion', on_delete= models.SET_NULL, null=True)
    responsableID = models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)

class Transporte(models.Model):
    idTransporte = models.IntegerField(primary_key= True, help_text= "ID unico para el tipo")
    empresaTransporte = models.CharField(max_length=30)
    medioTransporte = models.CharField(max_length=30)
    numeroMatricula = models.CharField(max_length=30)
    conductor = models.CharField(max_length=40)
    ruta = models.CharField(max_length=40)
    fechaSalida = models.CharField() 
    fechaLlegada = models.CharField()
    estadoTransporte = models.CharField(max_length=40)
    responsableID = models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)


class Control(models.Model):
    idControl = models.IntegerField(primary_key= True, help_text= "ID unico para el tipo")
    fechaInspeccion = models.CharField()
    horaInspeccion = models.CharField(max_length=20, default="00:00")
    tipoControl = models.CharField(max_length=30)
    resultadoInspeccion = models.CharField(max_length=30)
    descripcionHallazgos = models.CharField()
    idImportacion = models.ForeignKey('Importacion', on_delete=models.SET_NULL, null=True)
    idExportacion = models.ForeignKey('Exportacion', on_delete= models.SET_NULL, null=True)
    responsableID = models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)

class UsuarioBorrado(models.Model):
    nombreCompleto = models.CharField( max_length=30)
    rol = models.CharField( max_length=30)
    contrasena= models.CharField(max_length=128, default='123')
    ano_nacimiento=models.CharField(max_length=30, default='123')
    pais=models.CharField(max_length=30)
    telefono = models.CharField( max_length=30)
    correo = models.CharField( max_length=30)
    genero = models.CharField( max_length=30, default="")
    fecha_eliminacion = models.DateTimeField(auto_now_add=True)
    
class ImportacionBorrada(models.Model):
    idImportacion=models.IntegerField()
    fechaDeclaracion = models.CharField()
    proveedor = models.CharField( max_length=30)
    descripcionMercancia = models.CharField( max_length=100)
    codigoArancelario = models.BigIntegerField()
    cantidad = models.IntegerField()
    unidadMedida = models.CharField( max_length=30)
    valorCif = models.FloatField()
    impuestos = models.FloatField()
    origenMercancia = models.CharField( max_length=30)
    puertoEntrada = models.CharField( max_length=30)
    transporteID = models.ForeignKey('Transporte', on_delete=models.SET_NULL, null=True)
    responsableID = models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
    fecha_eliminacion = models.DateTimeField(auto_now_add=True)
    
class ExportacionBorrada(models.Model):
    idExportacion=models.IntegerField()
    fechaDeclaracion = models.CharField()
    cliente = models.CharField( max_length=30)
    descripcionMercancia = models.CharField( max_length=100)
    codigoArancelario = models.BigIntegerField()
    cantidad = models.IntegerField()
    unidadMedida = models.CharField( max_length=30)
    valorFob = models.IntegerField()
    impuestos = models.CharField( max_length=30)
    destinoMercancia = models.CharField( max_length=30)
    puertoSalida = models.CharField( max_length=30)
    transporteID = models.ForeignKey('Transporte', on_delete=models.SET_NULL, null=True)
    responsableID = models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
    fecha_eliminacion = models.DateTimeField(auto_now_add=True)
    
class CargaBorrado(models.Model):
    idCarga = models.IntegerField()
    tipoCarga = models.CharField(max_length=30)
    descripcionCarga = models.CharField(max_length=100)
    pesoBruto = models.DecimalField(max_digits=5, decimal_places=2)
    pesoNeto = models.DecimalField(max_digits=5, decimal_places=2)
    volumen = models.DecimalField(max_digits=5, decimal_places=2)
    embalaje = models.CharField( max_length=30)
    contenido = models.CharField( max_length=30)
    valorDeclarado =  models.FloatField()
    seguroCarga = models.FloatField()
    estadoCarga = models.CharField( max_length=30)
    idImportacion = models.ForeignKey('Importacion', on_delete=models.SET_NULL, null=True)
    idExportacion = models.ForeignKey('Exportacion', on_delete= models.SET_NULL, null=True)
    responsableID = models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
    fecha_eliminacion = models.DateTimeField(auto_now_add=True)

class TransporteBorrado(models.Model):
    idTransporte = models.IntegerField()
    empresaTransporte = models.CharField(max_length=30)
    medioTransporte = models.CharField(max_length=30)
    numeroMatricula = models.CharField(max_length=30)
    conductor = models.CharField(max_length=40)
    ruta = models.CharField(max_length=40)
    fechaSalida = models.CharField() 
    fechaLlegada = models.CharField()
    estadoTransporte = models.CharField(max_length=40)
    responsableID = models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
    fecha_eliminacion = models.DateTimeField(auto_now_add=True)


class ControlBorrado(models.Model):
    idControl = models.IntegerField()
    fechaInspeccion = models.CharField()
    horaInspeccion = models.CharField(max_length=20, default="00:00")
    tipoControl = models.CharField(max_length=30)
    resultadoInspeccion = models.CharField(max_length=30)
    descripcionHallazgos = models.CharField(max_length=30)
    idImportacion = models.ForeignKey('Importacion', on_delete=models.SET_NULL, null=True)
    idExportacion = models.ForeignKey('Exportacion', on_delete= models.SET_NULL, null=True)
    responsableID = models.ForeignKey('Usuario', on_delete=models.SET_NULL, null=True)
    fecha_eliminacion = models.DateTimeField(auto_now_add=True)