
from django.urls import path
from .views import *

urlpatterns = [
    path('inicio/', inicio, name='inicio'),
    path('servicios/', servicios, name='servicios'),
    path('registro_usuario/', registro_usuario, name='registro_usuario'),
    path('registro_usuario_is/', registro_usuario_is, name='registro_usuario_is'),
    path('registro_exitoso/', registro_exitoso, name='registro_exitoso'),
    path('registro_exitoso2/', registro_exitoso2, name='registro_exitoso2'),
    path('modificacion_exitosa/', modificacion_exitosa, name='modificacion_exitosa'),
    path('modificar_usuario/', modificar_usuario, name='modificar_usuario'),
    path('consultar_usuario/', consultar_usuario, name='consultar_usuario'),
    path('listar_usuarios/', listar_usuarios, name='listar_usuarios'),
    path('eliminar_usuario/', eliminar_usuario, name='eliminar_usuario'),
    path('registro_importacion/', registro_importacion, name='registro_importacion'),
    path('modificar_importacion/', modificar_importacion, name='modificar_importacion'),
    path('consultar_importacion/', consultar_importacion, name='consultar_importacion'),
    path('listar_importaciones/', listar_importaciones, name='listar_importaciones'),
    path('eliminar_importacion/', eliminar_importacion, name='eliminar_importacion'),
    path('iniciar_sesion/', iniciar_sesion, name='iniciar_sesion'),
    path('desautorizado/', desautorizado, name='desautorizado'),
    path('cerrar_sesion/', cerrar_sesion, name='cerrar_sesion'),
    path('registro_exportacion/', registro_exportacion, name='registro_exportacion'),
    path('consultar_exportacion/', consultar_exportacion, name='consultar_exportacion'),
    path('listar_exportaciones/', listar_exportaciones, name='listar_exportaciones'),
    path('eliminar_exportacion/', eliminar_exportacion, name='eliminar_exportacion'),
    path('modificar_exportacion/', modificar_exportacion, name='modificar_exportacion'),
    path('registro_transporte/', registro_transporte, name='registro_transporte'),
    path('listar_transporte/', listar_transporte, name='listar_transporte'),
    path('modificar_transporte/', modificar_transporte, name='modificar_transporte'),
    path('consultar_transporte/', consultar_transporte, name='consultar_transporte'),
    path('eliminar_transporte/', eliminar_transporte, name='eliminar_transporte'),
    path('registro_control/', registro_control, name='registro_control'),
    path('modificar_control/', modificar_control, name='modificar_control'),
    path('consultar_control/', consultar_control, name='consultar_control'),
    path('listar_control/', listar_control, name='listar_control'),
    path('eliminar_control/', eliminar_control, name='eliminar_control'),
    path('registro_carga/', registro_carga, name='registro_carga'),
    path('modificar_carga/', modificar_carga, name='modificar_carga'),
    path('consultar_carga/', consultar_carga, name='consultar_carga'),
    path('listar_carga/', listar_carga, name='listar_carga'),
    path('eliminar_carga/', eliminar_carga, name='eliminar_carga'),
    path('servicios_supervisor/', servicios_supervisor, name='servicios_supervisor'),
    path('consultar_usuarioS/', consultar_usuarioS, name='consultar_usuarioS'),
    path('listar_usuariosS/', listar_usuariosS, name='listar_usuariosS'),
    path('listar_importacionS/', listar_importacionS, name='listar_importacionS'),
    path('consultar_importacionS/', consultar_importacionS, name='consultar_importacionS'),
    path('consultar_exportacionS/', consultar_exportacionS, name='consultar_exportacionS'),
    path('listar_exportacionS/', listar_exportacionesS, name='listar_exportacionS'),
    path('listar_transporteS/', listar_transporteS, name='listar_transporteS'),
    path('consultar_transporteS/', consultar_transporteS, name='consultar_transporteS'),
    path('consultar_controlS/', consultar_controlS, name='consultar_controlS'),
    path('listar_controlS/', listar_controlS, name='listar_controlS'),
    path('listar_cargaS/', listar_cargaS, name='listar_cargaS'),
    path('consultar_cargaS/', consultar_cargaS, name='consultar_cargaS'),
    
    path('transporte-borrado/', listar_transporte_borrado, name='listar_transporte_borrado'),
    path('control-borrado/', listar_control_borrado, name='listar_control_borrado'),
    path('carga-borrado/', listar_carga_borrado, name='listar_carga_borrado'),
    path('borrados/',listar_borrados, name='listar_borrados'),
]   